name: incompatible_package_checker
description: Incompatible Package Checker, A helpful Flutter tool to scan for conflicting dependencies, preventing runtime errors. Boost your development efficiency
homepage: "https://smkwinner.vercel.app/"
version: 1.0.2
repository: https://github.com/Djsmk123/incompatible_package_checker_flutter

environment:
  sdk: '>=2.19.6 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  html: ^0.15.4
  http: ^1.1.0
  pubspec_parse: ^1.2.3
