name: incompatible_package_checker
description: Incompatible Package Checker for Flutter  The Incompatible Package Checker for Flutter is a useful tool for Flutter developers. This plugin scans your Flutter project for any incompatible packages or dependencies that may cause conflicts or errors during runtime.
homepage: "https://smkwinner.vercel.app/"
version: 1.0.1
repository: https://github.com/Djsmk123/incompatible_package_checker_flutter

environment:
  sdk: '>=2.19.6 <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  html: ^0.15.4
  http: ^0.13.6
  pubspec_parse: ^1.2.3
